// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD70c9R0eD6eDTjbWpXBsL2mFjctNiSjQs',
    appId: '1:844488863144:web:29e82f409e1fdca4ee819d',
    messagingSenderId: '844488863144',
    projectId: 'pro-icon-ems',
    authDomain: 'pro-icon-ems.firebaseapp.com',
    storageBucket: 'pro-icon-ems.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC61LeZ1LRD7Y1EbIfsoxMOh0QhijHhIZE',
    appId: '1:844488863144:android:56bbb34ade394bc3ee819d',
    messagingSenderId: '844488863144',
    projectId: 'pro-icon-ems',
    storageBucket: 'pro-icon-ems.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbfKKANPA8LCKVoDkAYicuKNghxGJKm2Q',
    appId: '1:844488863144:ios:8a9764b4f9e989aaee819d',
    messagingSenderId: '844488863144',
    projectId: 'pro-icon-ems',
    storageBucket: 'pro-icon-ems.firebasestorage.app',
    iosBundleId: 'com.example.proIcon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbfKKANPA8LCKVoDkAYicuKNghxGJKm2Q',
    appId: '1:844488863144:ios:8a9764b4f9e989aaee819d',
    messagingSenderId: '844488863144',
    projectId: 'pro-icon-ems',
    storageBucket: 'pro-icon-ems.firebasestorage.app',
    iosBundleId: 'com.example.proIcon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD70c9R0eD6eDTjbWpXBsL2mFjctNiSjQs',
    appId: '1:844488863144:web:f13921fa57f55da4ee819d',
    messagingSenderId: '844488863144',
    projectId: 'pro-icon-ems',
    authDomain: 'pro-icon-ems.firebaseapp.com',
    storageBucket: 'pro-icon-ems.firebasestorage.app',
  );
}
